### ISSUE TITLE
Make not working

### ISSUE THREAD

**Issue by gcjbr** [vmartins/Houaiss.dictionary#1]
When I try make here's what I get

`make
"""."/bin"/build_dict.sh"  "Houaiss" Houaiss.xml Houaiss.css Houaiss.plist
- Building Houaiss.dictionary.
- Cleaning objects directory.
- Preparing dictionary template.
- Preprocessing dictionary sources.
  ./bin/build_dict.sh: line 120: Houaiss.xml: No such file or directory
  Error.
  make: **\* [all] Error 1`

**Comment by ruriak** [comment]
Please explain better ... `make` command does not work ! 
How can I create the .dictionary file from .xml ?
Obrigado ;)

**Comment by meydjer** [comment]
Inside the master zip package is another zip package that you should unzip. Look:

1. https://cl.ly/1Z1T422D1I0o
2. https://cl.ly/1M2A2v3y3r3e
3. https://cl.ly/161l3y1J0a0Q

**Comment by Lavdsjvasdv** [comment]
Please upload the final file (Houaiss.dictionary), the make command still not working.

**Comment by vmartins** [comment]
> When I try make here's what I get
> 
> `make
> """."/bin"/build_dict.sh" "Houaiss" Houaiss.xml Houaiss.css Houaiss.plist
> 
> * Building Houaiss.dictionary.
> * Cleaning objects directory.
> * Preparing dictionary template.
> * Preprocessing dictionary sources.
>   ./bin/build_dict.sh: line 120: Houaiss.xml: No such file or directory
>   Error.
>   make: *** [all] Error 1`

First, unzip Houaiss.xml.zip. Follow the steps in [README](https://github.com/vmartins/Houaiss.dictionary/blob/master/README.md).

--

> Please upload the final file (Houaiss.dictionary), the make command still not working.

The ```make``` command still working and you can download on the [releases](https://github.com/vmartins/Houaiss.dictionary/releases) page.
